language: ruby

rvm: 2.0.0

env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - secure: "fc46Omc5RkSAspFXhyPr1uoT+evnOERetFaObShJA370Cm1oQkZUtH8IJ93GEUEGWJveK8ou0wpciYU8sSy3oNqThM1xJ3tegWFAwYv+NzBAgrbOMec/EkS16utkW8TDAqaPqf5sHRwV8XkeWNKYVDgzVTDE76npFzW2m3KrZ/Y="
  - secure: "QeXCE0SW3f4Y8vPXlGc9H66lCZ1s4GeSyeN0FS2uDNdQ2yHLsAWxrnzBYG4yhQWgr2PtZBQVN5uw7n4bT9UTEWgXUJJLL19GPt2jeiluRjfO7MoCg4NZRPC6nZHyqJEt++Qa1N8kQbISKv1fUOskZwp0ur10ToOmDy85poMdmPk="
  matrix:
  - SELENIUM_PLATFORM=MAC SELENIUM_BROWSER=chrome SELENIUM_VERSION=27 SELENIUM_BROWSER_URL="http://www.browserstack.com"
  - SELENIUM_PLATFORM=WIN8 SELENIUM_BROWSER=firefox SELENIUM_VERSION=24 SELENIUM_BROWSER_URL="http://www.browserstack.com"

before_script: gem install selenium-webdriver

script: ruby ruby/selenium_test.rb

